config/routes.rb
Rails.application.routes.draw do

  resources :parts

  resources :lineitems

  resources :orders

  resources :carts do
	resources :lineitems
  end

  get 'shop/index'

  resources :repairs

  get 'pages/home'

  get 'pages/about'
  
    resources :bikes do
		resources:repairs
	end

controller :sessions do
  get 'login' => :new
  post 'login' => :create
  get 'logout' => :destroy
  delete 'logout' => :destroy
  
  get 'customerlogin' => :customernew
  post 'customerlogin' => :customercreate
  get 'customerlogout' => :customerdestroy
  delete 'customerlogout' => :customerdestroy
  
  end

  
    
  get 'search', :to =>'parts#search'
 

  resources :customers

  resources :bikes

  resources :mechanics

  resources :categories

	root 'pages#home'
	

end

app/models/mechanic.rb
class Mechanic < ActiveRecord::Base
	has_many :repair, dependent: :destroy
	has_secure_password
	
	validates :name, presence: true
	validates :password, presence: true
	
	def self.search(query)
		where("name LIKE?", "%#{query}")
	end
end

app/controllers/mechanics_controller.rb
class MechanicsController < ApplicationController
  before_action :set_mechanic, only: [:show, :edit, :update, :destroy]
  before_action :authorise, :only  =>[:edit, :update, :delete]

  # GET /mechanics
  # GET /mechanics.json
  def index
    @mechanics = Mechanic.all
  end

  # GET /mechanics/1
  # GET /mechanics/1.json
  def show
  end

  def search
	@mechanics = Mechanic.search params[:query]
	unless @mechanics.empty?
		render 'index'
	else
		flash[:notice] = 'No record matches that search'
		render 'index'
	
	end
	
  end
  
  # GET /mechanics/new
  def new
    @mechanic = Mechanic.new
  end

  # GET /mechanics/1/edit
  def edit
  end

  # POST /mechanics
  # POST /mechanics.json
  def create
    @mechanic = Mechanic.new(mechanic_params)

    respond_to do |format|
      if @mechanic.save
        format.html { redirect_to @mechanic, notice: 'Mechanic was successfully created.' }
        format.json { render :show, status: :created, location: @mechanic }
      else
        format.html { render :new }
        format.json { render json: @mechanic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mechanics/1
  # PATCH/PUT /mechanics/1.json
  def update
    respond_to do |format|
      if @mechanic.update(mechanic_params)
        format.html { redirect_to @mechanic, notice: 'Mechanic was successfully updated.' }
        format.json { render :show, status: :ok, location: @mechanic }
      else
        format.html { render :edit }
        format.json { render json: @mechanic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mechanics/1
  # DELETE /mechanics/1.json
  def destroy
    @mechanic.destroy
    respond_to do |format|
      format.html { redirect_to mechanics_url, notice: 'Mechanic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mechanic
      @mechanic = Mechanic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mechanic_params
      params.require(:mechanic).permit(:name, :qualifications, :password, :password_confirmation, :email)
    end
end

app/helpers/mechanics_helper.rb
module MechanicsHelper
end

app/views/mechanics/_form.html.erb
<%= form_for(@mechanic) do |f| %>
  <% if @mechanic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mechanic.errors.count, "error") %> prohibited this mechanic from being saved:</h2>

      <ul>
      <% @mechanic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
   <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :qualifications %><br>
    <%= f.text_area :qualifications %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class = "field">
	 <%= f.label :passwordconfirmation %><br>
	 <%= f.password_field :password_confirmation %>
  </div>
	
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mechanics/edit.html.erb
<h1>Editing mechanic</h1>

<%= render 'form' %>

<%= link_to 'Show', @mechanic %> |
<%= link_to 'Back', mechanics_path %>

app/views/mechanics/index.html.erb
<style>
table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    text-align: left;
    padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}
</style>


<style>
h1 {
    text-align: center;
}

</style>
<h1>Listing mechanics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Qualifications</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mechanics.each do |mechanic| %>
      <tr>
        <td><%= mechanic.name %></td>
        <td><%= mechanic.qualifications %></td>
        <td><%= link_to 'Show', mechanic %></td>
        <td><%= link_to 'Edit', edit_mechanic_path(mechanic) %></td>
        <td><%= link_to 'Destroy', mechanic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mechanic', new_mechanic_path %>

app/views/mechanics/new.html.erb
<h1>New mechanic</h1>

<%= render 'form' %>

<%= link_to 'Back', mechanics_path %>

app/views/mechanics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mechanic.name %>
</p>

<p>
  <strong>Qualifications:</strong>
  <%= @mechanic.qualifications %>
</p>


<%= link_to 'Edit', edit_mechanic_path(@mechanic) %> |
<%= link_to 'Back', mechanics_path %>