config/routes.rb
Rails.application.routes.draw do

  resources :parts

  resources :lineitems

  resources :orders

  resources :carts do
	resources :lineitems
  end

  get 'shop/index'

  resources :repairs

  get 'pages/home'

  get 'pages/about'
  
    resources :bikes do
		resources:repairs
	end

controller :sessions do
  get 'login' => :new
  post 'login' => :create
  get 'logout' => :destroy
  delete 'logout' => :destroy
  
  get 'customerlogin' => :customernew
  post 'customerlogin' => :customercreate
  get 'customerlogout' => :customerdestroy
  delete 'customerlogout' => :customerdestroy
  
  end

  
    
  get 'search', :to =>'parts#search'
 

  resources :customers

  resources :bikes

  resources :mechanics

  resources :categories

	root 'pages#home'
	

end

app/models/bike.rb
class Bike < ActiveRecord::Base
	has_many :repairs
	has_many :lineitems
	
	
	validates :name, presence: true
	validates :maker, presence: true
	validates :price, presence: true
	validates :picture, presence: true
	


	has_many :repairs, dependent: :destroy
	belongs_to :category
	belongs_to :customer
	
	def self.search(query)
		where("name LIKE?", "%#{query} %")
	
	end
	
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :set_bike, only: [:show, :edit, :update, :destroy]
  before_action :authorise, :only  =>[:edit, :update, :delete]

  # GET /bikes
  # GET /bikes.json
  def index
    @bikes = Bike.all
  end

  # GET /bikes/1
  # GET /bikes/1.json
  def show
  end
  
    def search
	@bikes = Bike.search params[:query]
	unless @bikes.empty?
		render 'index'
	else
		flash[:notice] = 'No record matches that search'
		render 'index'
	
	end
	
  end


  # GET /bikes/new
  def new
    @bike = Bike.new
  end

  # GET /bikes/1/edit
  def edit
  end

  # POST /bikes
  # POST /bikes.json
  def create
    @bike = Bike.new(bike_params)

    respond_to do |format|
      if @bike.save
        format.html { redirect_to @bike, notice: 'Bike was successfully created.' }
        format.json { render :show, status: :created, location: @bike }
      else
        format.html { render :new }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bikes/1
  # PATCH/PUT /bikes/1.json
  def update
    respond_to do |format|
      if @bike.update(bike_params)
        format.html { redirect_to @bike, notice: 'Bike was successfully updated.' }
        format.json { render :show, status: :ok, location: @bike }
      else
        format.html { render :edit }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bikes/1
  # DELETE /bikes/1.json
  def destroy
    @bike.destroy
    respond_to do |format|
      format.html { redirect_to bikes_url, notice: 'Bike was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bike
      @bike = Bike.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bike_params
      params.require(:bike).permit(:name, :maker, :size, :price, :description, :picture, :category_id, :customer_id)
    end
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/views/bikes/_form.html.erb
<%= form_for(@bike) do |f| %>
  <% if @bike.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bike.errors.count, "error") %> prohibited this bike from being saved:</h2>

      <ul>
      <% @bike.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :maker %><br>
    <%= f.text_field :maker %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name%>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.collection_select :customer_id, Customer.all, :id, :name%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bikes/edit.html.erb
<h1>Editing bike</h1>

<%= render 'form' %>

<%= link_to 'Show', @bike %> |
<%= link_to 'Back', bikes_path %>

app/views/bikes/index.html.erb
<style>
table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    text-align: left;
    padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}
</style>
<div>

<style>
h1 {
    text-align: center;
}

</style>

<h1>Listing bikes</h1>

</div>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Maker</th>
      <th>Size</th>
      <th>Price</th>
      <th>Description</th>
      <th>Picture</th>
      <th>Category</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bikes.each do |bike| %>
      <tr>
        <td><%= bike.name %></td>
        <td><%= bike.maker %></td>
        <td><%= bike.size %></td>
        <td><%= bike.price %></td>
        <td><%= bike.description %></td>
        <td><%= image_tag(bike.picture,:size=>"80x50")%></td>
        <td><%= bike.category.name %></td>
        <td><%= bike.customer.name %></td>
        <td><%= link_to 'Show', bike %></td>
        <td><%= link_to 'Edit', edit_bike_path(bike) %></td>
        <td><%= link_to 'Destroy', bike, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bike', new_bike_path %>

app/views/bikes/new.html.erb
<h1>New bike</h1>

<%= render 'form' %>

<%= link_to 'Back', bikes_path %>

app/views/bikes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bike.name %>
</p>

<p>
  <strong>Maker:</strong>
  <%= @bike.maker %>
</p>

<p>
  <strong>Size:</strong>
  <%= @bike.size %>
</p>

<p>
  <strong>Price:</strong>
  <%= @bike.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @bike.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @bike.picture %>
</p>

<p>
  <strong>Category:</strong>
  <%= @bike.category.name %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @bike.customer.name %>
</p>

<h2> Repairs for this bike </h2>
	<%=form_for([@bike, Repair.new]) do |f| %>
	<%=f.text_area :problem, :rows =>3, :cols => 40 %>
	<div class = "actions">
		<%=f.submit "Post Repair" %>
	</div>
<%end%>

<%if @bike.repairs.empty? %>
	<h3> You are the first to comment </h3>
<%else%>
		<h2> Previous Problems </h2>
		<%@bike.repairs.reverse.each do |repair| %>
				<p><%=repair.problem%>
				Posted <%=time_ago_in_words(repair.created_at) %> ago by
				<%=repair.mechanic.name%> </p>
			<%end%>
<%end%>



<%= link_to 'Edit', edit_bike_path(@bike) %> |
<%= link_to 'Back', bikes_path %>