config/routes.rb
Rails.application.routes.draw do

  resources :parts

  resources :lineitems

  resources :orders

  resources :carts do
	resources :lineitems
  end

  get 'shop/index'

  resources :repairs

  get 'pages/home'

  get 'pages/about'
  
    resources :bikes do
		resources:repairs
	end

controller :sessions do
  get 'login' => :new
  post 'login' => :create
  get 'logout' => :destroy
  delete 'logout' => :destroy
  
  get 'customerlogin' => :customernew
  post 'customerlogin' => :customercreate
  get 'customerlogout' => :customerdestroy
  delete 'customerlogout' => :customerdestroy
  
  end

  
    
  get 'search', :to =>'parts#search'
 

  resources :customers

  resources :bikes

  resources :mechanics

  resources :categories

	root 'pages#home'
	

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kev's Bike Shop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
<link href="https://blackrockdigital.github.io/full-width-pics.css" rel="stylesheet">
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" <%= link_to "KOD Bike Shop", root_path%></a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to "Home",root_path%></li>
      <li class="active"><%= link_to "Bikes",bikes_path%></li>
      <li class="active"><%= link_to "Mechanics",mechanics_path%></li>
	  <li class="active"><%= link_to "Instructions for Parts",parts_path%></li>
	  
	  
	  
		
		<%if !customersigned_in? %>
			<li><%=link_to "Customer Sign in", customerlogin_path %></li>
		<% else %>
			<li>Signed in as <%=@current_customer.name %></li>
			<li><%=link_to "Sign Out",customerlogout_path %></li>
		<% end %>
		
		<%= render '/parts/search' %>
		
		
    </ul>
  </div>
</nav>

</div>


<%= yield %>

<footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1 text-center">
                    <h4><strong>Start Bootstrap</strong>
                    </h4>
                    <p>DIT Aungier Street
                        <br>Dublin</p>
						<p><%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{53.3386609}%2C#{-6.2698335}" %></p>
                    <ul class="list-unstyled">
                        <li><i class="fa fa-phone fa-fw"></i> (123) 456-7890</li>
                        <li><i class="fa fa-envelope-o fa-fw"></i> <a href="mailto:name@example.com">name@example.com</a>
                        </li>
                    </ul>
                    <br>
                    <ul class="list-inline">
                        <li>
                            <a href="#"><i class="fa fa-facebook fa-fw fa-3x"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-twitter fa-fw fa-3x"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-dribbble fa-fw fa-3x"></i></a>
                        </li>
                    </ul>
					<h1>
                    <%if !signed_in? %>
						<li><%=link_to "Mechanic Sign in", login_path %></li>
					<% else %>
						<li>Signed in as <%=@current_mechanic.name %></li>
						<li><%=link_to "Sign Out",logout_path %></li>
					<% end %>
					</h1>
			</div>
        </div>
        <a id="to-top" href="#top" class="btn btn-dark btn-lg"><i class="fa fa-chevron-up fa-fw fa-1x"></i></a>
    </footer>

	<% flash.each do |key, value| %>
		<%= content_tag(:p, value, :class => "flash #{key}") %>
	<% end %>

</body>
</html>